server:
  port: 7001
  servlet:
    context-path: /coupon-template

spring:
  application:
    name: coupon-template
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    # 数据源
    url: jdbc:mysql://127.0.0.1:3306/coupon_data?autoReconnect=true&useUnicode
    username: root
    password: uhU1cfQ192K-9
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    # 连接池
    hikari:
      max-lifetime: 4500
      maximum-pool-size: 8
      minimum-idle: 4
      connection-timeout: 30000
      idle-timeout: 30000
      auto-commit: true
      pool-name: CouponHikariCP

  redis:
    database: 0
    host: 47.115.131.250
    port: 6379
    timeout: 10000

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

logging:
  level:
    com.woo.coupon: debug
